sm6225-common: nuke wfd jar for now
error: frameworks/base/boot/Android.bp:44:1: "platform-bootclasspath" depends on undefined module "WfdCommon"
Module "platform-bootclasspath" is defined in namespace "." which can read these 1 namespaces: ["."]
Module "WfdCommon" can be found in these namespaces: ["vendor/xiaomi/sm6225-common"]

Signed-off-by: Dmitrii <bankersenator@gmail.com>
Signed-off-by: Pranav Temkar <pranavtemkar@gmail.com>
Signed-off-by: Iverz <asterixiverz@gmail.com>